/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.Usuario;
import javax.swing.JOptionPane;
import java.util.InputMismatchException;
/**
 *
 * @author dell
 */
public class UsuarioDeleteJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioDeleteJPanel
     */
    public UsuarioDeleteJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        container_content = new javax.swing.JPanel();
        content_header = new javax.swing.JPanel();
        content_title = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldCi = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        content_header1 = new javax.swing.JPanel();
        content_title1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCI = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(600, 400));

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(30, 33, 44));
        title.setText("Clientes");

        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setForeground(new java.awt.Color(51, 51, 51));
        description.setText("Este módulo elimina a todos los clientes .");

        container_content.setBackground(new java.awt.Color(255, 255, 255));
        container_content.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 244, 247), 2, true));

        content_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        content_title.setText("Eliminar Clientes");

        javax.swing.GroupLayout content_headerLayout = new javax.swing.GroupLayout(content_header);
        content_header.setLayout(content_headerLayout);
        content_headerLayout.setHorizontalGroup(
            content_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(content_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_headerLayout.setVerticalGroup(
            content_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_title)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButtonEliminar.setBackground(new java.awt.Color(0, 123, 255));
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setBorder(null);
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonBuscar.setBackground(new java.awt.Color(3, 206, 164));
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTextFieldCi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabelEmail1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEmail1.setText("CI :");

        content_title1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        content_title1.setText("Datos :");

        javax.swing.GroupLayout content_header1Layout = new javax.swing.GroupLayout(content_header1);
        content_header1.setLayout(content_header1Layout);
        content_header1Layout.setHorizontalGroup(
            content_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(content_title1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_header1Layout.setVerticalGroup(
            content_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_title1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre:");

        jLabel2.setBackground(new java.awt.Color(0, 123, 255));
        jLabel2.setText("CI :");

        jLabel3.setText("Apelido");

        jLabelCI.setText("0000000000");

        jLabelNombre.setText("s/n");

        jLabelApellido.setText("s/n");

        javax.swing.GroupLayout container_contentLayout = new javax.swing.GroupLayout(container_content);
        container_content.setLayout(container_contentLayout);
        container_contentLayout.setHorizontalGroup(
            container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(container_contentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelEmail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(jTextFieldCi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(content_header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(container_contentLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCI, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        container_contentLayout.setVerticalGroup(
            container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_contentLayout.createSequentialGroup()
                .addComponent(content_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEmail1)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldCi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(content_header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_contentLayout.createSequentialGroup()
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelCI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelApellido)))
                    .addGroup(container_contentLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description)
                    .addComponent(title))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(description)
                .addGap(18, 18, 18)
                .addComponent(container_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 361, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
       try {
    // Obtener el CI del campo de texto
    int ci = Integer.parseInt(jTextFieldCi.getText());

    // Eliminar el usuario por CI
    Usuario.eliminarUsuario(String.valueOf(ci));

    // Mostrar mensaje de éxito
    JOptionPane.showMessageDialog(this, "Usuario eliminado de la DB con éxito");

    // Limpiar los campos y labels
    jTextFieldCi.setText("");
    jLabelCI.setText("s/n");
    jLabelNombre.setText("s/n");
    jLabelApellido.setText("s/n");
} catch (NumberFormatException e) {
    // Manejar la excepción si el CI no es un número válido
    JOptionPane.showMessageDialog(this, "Ingrese un CI válido");
}
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
      try {
        // Obtener el CI del campo de texto
        int ci = Integer.parseInt(jTextFieldCi.getText());

        // Buscar el usuario por CI
        Usuario usuario = Usuario.getUserById(String.valueOf(ci));

        // Mostrar la información en los labels
        if (usuario != null) {
            jLabelCI.setText(String.valueOf(usuario.getCi()));
            jLabelNombre.setText(usuario.getNombre());
            jLabelApellido.setText(usuario.getApellido());
        } else {
            // Si el usuario no existe, mostrar un mensaje
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            jLabelCI.setText("s/n");
            jLabelNombre.setText("s/n");
            jLabelApellido.setText("s/n");
        }
    } catch (NumberFormatException e) {
        // Manejar la excepción si el CI no es un número válido
        JOptionPane.showMessageDialog(this, "Ingrese un CI válido");
    }       
      
    }//GEN-LAST:event_jButtonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel container_content;
    private javax.swing.JPanel content_header;
    private javax.swing.JPanel content_header1;
    private javax.swing.JLabel content_title;
    private javax.swing.JLabel content_title1;
    private javax.swing.JLabel description;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCI;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextFieldCi;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
